- name: Action Auto Changelog
  uses: ahmadawais/action-auto-changelog@1.0.0
  with:
    # Token for the repo. Can be passed in using $\{{ secrets.GITHUB_TOKEN }}
    github_token: 
    # Repository name to push. Default or empty value represents current github repository (${GITHUB_REPOSITORY})
    repository: # optional, default is 
    # Destination branch to push changes
    branch: # optional, default is master
    # Determines if force push is used
    force: # optional
    # Determines if --tags is used
    tags: # optional
    # Directory to change to before pushing.
    directory: # optional, default is .
