name: Changelog Generator
on:
  # Trigger the workflow on pull request,
  # but only for the master branch
  pull_request:
    branches:
      - master
    types: [opened, reopened, synchronize]

jobs:
  changelog:
    # Job name is Chanegelog
    name: Chanegelog Generator
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          with:
            node-version: '10.x' 
        - name: Dependency installer
          id: changelogDep
          run: |
            npm ci
        - name: Changelog Generator
          id: changelogGen
          run: npm run changelog
          env: 
            token: ${{ secrets.GITHUB_TOKEN }}
